server:
  port: 80
  error:
    whitelabel:
      enabled: false
spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    template-resolver-order: 0
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521/xe
    username: cafe_user
    password: 123456
mybatis:
  type-aliases-package: kr.co.dbcafe.vo
  mapper-locations: classpath:mappers/**/*.xml